version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}


workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - fail_test
        
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: echo-content
          command: 'echo "TESTE PERSISTÊNCIA" > /tmp/output.txt'
      
      - persist_to_workspace:
          root: /tmp
          paths:
            - output.txt
      - print_pipeline_id

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: cat-content
          command: 'cat /tmp/output.txt'
      - print_pipeline_id
  
  fail_test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run: 
          name: Print Failed Testes
          command: echo "O teste falhouuuuu!!!!"
          when: on_fail
      