version: 2.1

workflows:
  version: 2
  save_hello_world_output:
    jobs:
      - save_hello_world_output
  print_output_file:
    requires:
      - save_hello_world_output
    jobs:
      - print_output_file
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/ubuntu-server
    steps:
      - run:
          name: echo-content
          command: 'echo "TESTE PERSISTÊNCIA" > /tmp/output.txt'
      
      - persist_to_workspace:
          root: /tmp
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/ubuntu-server
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: cat-content
          command: 'cat /tmp/output.txt'